/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import PrimaryLogo1Image from 'src/assets/images/navbar_primary_logo_1.png';
import { styled } from '@mui/material/styles';
import useNavBar from 'src/components/NavBar/useNavBar';

const ScreenDesktop = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: 'auto',
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `8px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const LeftSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const PrimaryLogo1 = styled('img')({
  height: `42px`,
  width: `237px`,
  objectFit: `cover`,
  margin: `0px`,
});

const RightSide = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Hamburger = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `16px`,
  margin: `0px`,
});

const MenuRectangle1 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  width: `24px`,
  height: `3.2px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const MenuRectangle11 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  width: `24px`,
  height: `3.2px`,
  position: `absolute`,
  left: `0px`,
  top: `6px`,
});

const MenuRectangle12 = styled('div')({
  backgroundColor: `rgba(0, 0, 0, 1)`,
  width: `24px`,
  height: `3.2px`,
  position: `absolute`,
  left: `0px`,
  top: `13px`,
});

const Home = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rubik`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
}));

const Shop = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rubik`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
}));

const Deals = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rubik`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
}));

const Contact = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rubik`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
}));

const Button1 = styled('div')({
  backgroundColor: `rgba(0, 0, 255, 1)`,
  borderRadius: `25px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 16px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 16px`,
  overflow: `hidden`,
});

const CallNow = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rubik`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

function NavBar(props) {
  const { data } = useNavBar();

  return (
    <ScreenDesktop className={props.className}>
      <LeftSide>
        <PrimaryLogo1
          src={PrimaryLogo1Image}
          loading="lazy"
          alt={'primary_logo 1'}
        />
      </LeftSide>
      <RightSide>
        <Hamburger>
          <MenuRectangle1></MenuRectangle1>
          <MenuRectangle11></MenuRectangle11>
          <MenuRectangle12></MenuRectangle12>
        </Hamburger>
        {!(data.currentVariant === 'ScreenMobile') && <Home>{`Home`}</Home>}
        {!(data.currentVariant === 'ScreenMobile') && <Shop>{`Shop`}</Shop>}
        {!(data.currentVariant === 'ScreenMobile') && <Deals>{`Deals`}</Deals>}
        {!(data.currentVariant === 'ScreenMobile') && (
          <Contact>{`Contact`}</Contact>
        )}
        {!(data.currentVariant === 'ScreenMobile') && (
          <Button1>
            <CallNow>{`Call now`}</CallNow>
          </Button1>
        )}
      </RightSide>
    </ScreenDesktop>
  );
}

export default NavBar;
